cat << 'PATCH' > LogicBlockManager.java.patch
<<<<<<< SEARCH
    // Page-based events (Sketchware pattern)
    public static final String EVENT_PAGE_LOAD = "pageLoad";
    public static final String EVENT_VISIBLE = "visible";
    public static final String EVENT_HIDDEN = "hidden";
    public static final String EVENT_DESTROY = "destroy";
    public static final String EVENT_PAGE_SCROLL = "pageScroll";
    public static final String EVENT_PAGE_INPUT = "pageInput";

    // Element events
    public static final String EVENT_CLICK = "click";
    public static final String EVENT_HOVER = "hover";
    public static final String EVENT_INPUT = "input";
    public static final String EVENT_LOAD = "load";
    public static final String EVENT_SUBMIT = "submit";
    public static final String EVENT_SCROLL = "scroll";
    public static final String EVENT_KEYDOWN = "keydown";
    public static final String EVENT_CHANGE = "change";

    public static final String ACTION_CHANGE_STYLE = "changeStyle";
=======
    // CSS Pseudo-class events
    public static final String EVENT_HOVER = "hover";
    public static final String EVENT_FOCUS = "focus";
    public static final String EVENT_ACTIVE = "active";

    // CSS actions
    public static final String ACTION_SET_DISPLAY = "setDisplay";
    public static final String ACTION_SET_POSITION = "setPosition";
    public static final String ACTION_SET_COLOR = "setColor";
    public static final String ACTION_SET_BACKGROUND = "setBackground";
    public static final String ACTION_SET_MARGIN = "setMargin";
    public static final String ACTION_SET_PADDING = "setPadding";
    public static final String ACTION_SET_BORDER = "setBorder";
    public static final String ACTION_SET_RADIUS = "setRadius";
    public static final String ACTION_SET_OPACITY = "setOpacity";
    public static final String ACTION_SET_FONT_SIZE = "setFontSize";
    public static final String ACTION_SET_TEXT_ALIGN = "setTextAlign";
    public static final String ACTION_SET_ZINDEX = "setZIndex";
    public static final String ACTION_SET_FLEX = "setFlex";
    public static final String ACTION_SET_TRANSFORM = "setTransform";
    public static final String ACTION_SET_TRANSITION = "setTransition";

    // HTML Attributes actions
    public static final String ACTION_SET_HREF = "setHref";
    public static final String ACTION_SET_SRC = "setSrc";
    public static final String ACTION_SET_ATTRIBUTE = "setAttribute";
    public static final String ACTION_SET_ID = "setId";
    public static final String ACTION_SET_CLASS = "setClass";
>>>>>>> REPLACE
<<<<<<< SEARCH
    public String generateJavaScript() {
        if (blocks.isEmpty()) return "";

        StringBuilder js = new StringBuilder();
        js.append("// Logic blocks generated by DragWeb\n");
        js.append("document.addEventListener('DOMContentLoaded', function() {\n");
=======
    public String generateJavaScript() {
        return ""; // Logic blocks no longer generate JS
    }

    public String generatePseudoClassCss() {
        if (blocks.isEmpty()) return "";

        StringBuilder css = new StringBuilder();
        Map<String, StringBuilder> pseudoStyles = new HashMap<>();

        for (LogicBlock block : blocks) {
            String eventName = block.event;
            if (EVENT_HOVER.equals(eventName) || EVENT_FOCUS.equals(eventName) || EVENT_ACTIVE.equals(eventName)) {
                String selector = buildSelector(block) + ":" + eventName;
                if (!pseudoStyles.containsKey(selector)) {
                    pseudoStyles.put(selector, new StringBuilder());
                }

                String cssRule = generateActionCss(block);
                if (cssRule != null && !cssRule.isEmpty()) {
                    pseudoStyles.get(selector).append("  ").append(cssRule).append("\n");
                }
            }
        }

        for (Map.Entry<String, StringBuilder> entry : pseudoStyles.entrySet()) {
            css.append(entry.getKey()).append(" {\n");
            css.append(entry.getValue().toString());
            css.append("}\n\n");
        }

        return css.toString();
    }

    private String generateActionCss(LogicBlock block) {
        String val = block.params;
        switch (block.action) {
            case ACTION_SET_DISPLAY: return "display: " + val + ";";
            case ACTION_SET_POSITION: return "position: " + val + ";";
            case ACTION_SET_COLOR: return "color: " + val + ";";
            case ACTION_SET_BACKGROUND: return "background: " + val + ";";
            case ACTION_SET_MARGIN: return "margin: " + val + ";";
            case ACTION_SET_PADDING: return "padding: " + val + ";";
            case ACTION_SET_BORDER: return "border: " + val + ";";
            case ACTION_SET_RADIUS: return "border-radius: " + val + ";";
            case ACTION_SET_OPACITY: return "opacity: " + val + ";";
            case ACTION_SET_FONT_SIZE: return "font-size: " + val + ";";
            case ACTION_SET_TEXT_ALIGN: return "text-align: " + val + ";";
            case ACTION_SET_ZINDEX: return "z-index: " + val + ";";
            case ACTION_SET_FLEX: return "flex: " + val + ";";
            case ACTION_SET_TRANSFORM: return "transform: " + val + ";";
            case ACTION_SET_TRANSITION: return "transition: " + val + ";";
            default: return null;
        }
>>>>>>> REPLACE
PATCH
