import re

with open('source/app/src/main/java/sketchweb/gl/LogicBlockManager.java', 'r') as f:
    content = f.read()

# Replace generateJavaScript method to wrap logic in page-level scopes based on events
old_generate_js = """    public String generateJavaScript() {
        if (blocks.isEmpty()) return "";

        StringBuilder js = new StringBuilder();
        js.append("// Logic blocks generated by DragWeb\\n");
        js.append("document.addEventListener('DOMContentLoaded', function() {\\n");

        for (LogicBlock block : blocks) {
            String eventName = block.event;

            js.append("  // ").append(block.event).append(" -> ").append(block.action).append("\\n");

            // Immediate blocks (logic/variable) - execute inline, no event listener
            if ("immediate".equals(eventName)) {
                js.append("  ").append(generateActionJs(block, "document.body"));
                js.append("\\n");
            } else if (EVENT_LOAD.equals(eventName)) {
                String selector = buildSelector(block);
                js.append("  (function() {\\n");
                js.append("    ").append(generateActionJs(block, "document.body"));
                js.append("  })();\\n\\n");
            } else {
                String selector = buildSelector(block);
                String jsEvent = eventName;
                if ("hover".equals(eventName)) jsEvent = "mouseenter";

                js.append("  document.querySelectorAll('").append(selector).append("').forEach(function(el) {\\n");
                js.append("    el.addEventListener('").append(jsEvent).append("', function(event) {\\n");
                js.append("      ").append(generateActionJs(block, "el"));
                js.append("    });\\n");
                js.append("  });\\n\\n");
            }
        }

        js.append("});\\n");
        return js.toString();
    }"""

new_generate_js = """    public String generateJavaScript() {
        if (blocks.isEmpty()) return "";

        StringBuilder js = new StringBuilder();
        js.append("// Logic blocks generated by DragWeb\\n");

        // Define page load function
        js.append("document.addEventListener('DOMContentLoaded', function() {\\n");

        for (LogicBlock block : blocks) {
            String eventName = block.event;

            if ("immediate".equals(eventName)) {
                js.append("  ").append(generateActionJs(block, "document.body"));
            } else if ("onPageLoad".equals(eventName) || EVENT_LOAD.equals(eventName)) {
                js.append("  (function() {\\n");
                if (block.targetMode != null && !block.targetMode.isEmpty() && block.targetWidget != null && !block.targetWidget.isEmpty()) {
                     js.append("    document.querySelectorAll('").append(buildSelector(block)).append("').forEach(function(el) {\\n");
                     js.append("      ").append(generateActionJs(block, "el"));
                     js.append("    });\\n");
                } else {
                     js.append("    ").append(generateActionJs(block, "document.body"));
                }
                js.append("  })();\\n\\n");
            } else if ("onVisible".equals(eventName)) {
                String selector = buildSelector(block);
                js.append("  var observer = new IntersectionObserver(function(entries) {\\n");
                js.append("    entries.forEach(function(entry) {\\n");
                js.append("      if(entry.isIntersecting) {\\n");
                js.append("        var el = entry.target;\\n");
                js.append("        ").append(generateActionJs(block, "el"));
                js.append("      }\\n");
                js.append("    });\\n");
                js.append("  });\\n");
                js.append("  document.querySelectorAll('").append(selector).append("').forEach(function(el) { observer.observe(el); });\\n\\n");
            } else if ("onHidden".equals(eventName)) {
                String selector = buildSelector(block);
                js.append("  var observer = new IntersectionObserver(function(entries) {\\n");
                js.append("    entries.forEach(function(entry) {\\n");
                js.append("      if(!entry.isIntersecting) {\\n");
                js.append("        var el = entry.target;\\n");
                js.append("        ").append(generateActionJs(block, "el"));
                js.append("      }\\n");
                js.append("    });\\n");
                js.append("  });\\n");
                js.append("  document.querySelectorAll('").append(selector).append("').forEach(function(el) { observer.observe(el); });\\n\\n");
            } else if ("onDestroy".equals(eventName)) {
                js.append("  window.addEventListener('beforeunload', function() {\\n");
                js.append("    var el = document.body;\\n");
                js.append("    ").append(generateActionJs(block, "el"));
                js.append("  });\\n\\n");
            } else {
                String selector = buildSelector(block);
                String jsEvent = eventName;
                if ("hover".equals(eventName) || "onHover".equals(eventName)) jsEvent = "mouseenter";
                else if ("click".equals(eventName) || "onClick".equals(eventName)) jsEvent = "click";
                else if ("input".equals(eventName) || "onInput".equals(eventName)) jsEvent = "input";
                else if ("submit".equals(eventName) || "onSubmit".equals(eventName)) jsEvent = "submit";
                else if ("scroll".equals(eventName) || "onScroll".equals(eventName)) jsEvent = "scroll";

                js.append("  document.querySelectorAll('").append(selector).append("').forEach(function(el) {\\n");
                js.append("    el.addEventListener('").append(jsEvent).append("', function(event) {\\n");
                js.append("      ").append(generateActionJs(block, "this"));
                js.append("    });\\n");
                js.append("  });\\n\\n");
            }
        }

        js.append("});\\n");
        return js.toString();
    }"""

content = content.replace(old_generate_js, new_generate_js)

with open('source/app/src/main/java/sketchweb/gl/LogicBlockManager.java', 'w') as f:
    f.write(content)
