package sketchweb.gl;

import android.content.Context;
import android.os.Environment;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.BufferedOutputStream;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.ArrayList;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class ExportManager {

    private Context context;
    private ThemeManager themeManager;
    private IconLibraryManager iconLibraryManager;
    private AnimationLibraryManager animationLibraryManager;
    private String projectId;

    /**
     * Per-export accumulator for element-level CSS. Cleared at the start of
     * each call to {@link #generateExportFiles} so widget styles get appended
     * into {@code css/style.css} instead of being baked inline on the element.
     */
    private final StringBuilder elementCssBuffer = new StringBuilder();

    public ExportManager(Context context, ThemeManager themeManager) {
        this.context = context;
        this.themeManager = themeManager;
    }

    public void setIconLibraryManager(IconLibraryManager m) {
        this.iconLibraryManager = m;
    }

    public void setAnimationLibraryManager(AnimationLibraryManager m) {
        this.animationLibraryManager = m;
    }

    /**
     * Set the active project id so non-ZIP exports can locate the matching
     * assets folder ({@code .dragweb/projects/&lt;id&gt;/assets}). Without this
     * the HTML export still works, but ships with an empty assets directory.
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public static class ExportResult {
        public String htmlContent;
        public String cssContent;
        public String jsContent;
        public File exportDir;
        public boolean success;
        public String message;
    }

    public ExportResult generateExportFiles(View screen, String projectName, LogicBlockManager logicBlockManager) {
        return generateExportFiles(screen, projectName, logicBlockManager, null);
    }

    public ExportResult generateExportFiles(View screen, String projectName,
                                            LogicBlockManager logicBlockManager,
                                            ManageBlocksWidgets customBlockManager) {
        ExportResult result = new ExportResult();
        
        // Load all project pages using PageManager
        PageManager pageManager = new PageManager(context, projectId);
        List<String> allPages = pageManager.getPages();
        if (allPages.isEmpty()) {
            allPages.add("index");
        }
        String currentPageName = pageManager.getCurrentPage();

        Map<String, String> pageHtmlMap = new HashMap<>();
        StringBuilder accumulatedCssBuffer = new StringBuilder();
        StringBuilder accumulatedJsBuffer = new StringBuilder();

        // 1. Theme variables, presets, and common styles in CSS
        accumulatedCssBuffer.append("/* Generated by DragWeb */\n\n");
        accumulatedCssBuffer.append(themeManager.generateGlobalCss());
        accumulatedCssBuffer.append("\n/* Animation Keyframes */\n");
        if (animationLibraryManager != null) {
            accumulatedCssBuffer.append(animationLibraryManager.generateLocalKeyframesCss(""));
        } else {
            accumulatedCssBuffer.append(AnimationLibrary.generateKeyframesCss(""));
        }
        accumulatedCssBuffer.append("\n");

        // 2. Common JS header
        accumulatedJsBuffer.append("/* ==========================================================\n");
        accumulatedJsBuffer.append(" * DragWeb generated runtime — DO NOT edit by hand.\n");
        accumulatedJsBuffer.append(" * Sections: state, init, events, api, animations.\n");
        accumulatedJsBuffer.append(" * ========================================================== */\n\n");
        accumulatedJsBuffer.append("'use strict';\n\n");
        accumulatedJsBuffer.append("/* ----- state ----- */\n");
        accumulatedJsBuffer.append("var DW = window.DW = window.DW || { state: {}, components: {} };\n\n");

        elementCssBuffer.setLength(0);

        for (String pageName : allPages) {
            String htmlContent = "";
            LogicBlockManager pageLogic = null;

            if (pageName.equals(currentPageName)) {
                // Live page
                htmlContent = generateHtml(screen, projectName, customBlockManager, logicBlockManager);
                pageLogic = logicBlockManager;
            } else {
                // Loaded page from json
                String pageJson = pageManager.loadPageLayout(pageName);
                pageLogic = new LogicBlockManager(context);
                File dir = new File(context.getFilesDir(), "projects");
                File logicFile = new File(dir, projectId + "_" + pageName + ".logic");
                if (logicFile.exists()) {
                    String logicJson = FileUtil.readFile(logicFile.getAbsolutePath());
                    pageLogic.fromJson(logicJson);
                }

                List<Map<String, Object>> widgetTree = null;
                try {
                    widgetTree = new com.google.gson.Gson().fromJson(pageJson,
                        new com.google.gson.reflect.TypeToken<List<Map<String, Object>>>(){}.getType());
                } catch (Exception e) {
                    Log.w("ExportManager", "Error parsing widget tree for page: " + pageName, e);
                }
                htmlContent = generateHtmlFromTree(widgetTree, pageName, customBlockManager, pageLogic);
            }

            // Clean assets reference in HTML: replace "assets/" with ""
            htmlContent = htmlContent.replace("assets/", "");

            pageHtmlMap.put(pageName, htmlContent);

            // Accumulate page-specific CSS rules
            if (pageLogic != null) {
                String pseudoRules = pageLogic.generateCssPseudoRules();
                if (pseudoRules != null && !pseudoRules.trim().isEmpty()) {
                    accumulatedCssBuffer.append("/* CSS Interaction Rules for ").append(pageName).append(" */\n");
                    accumulatedCssBuffer.append(pseudoRules).append("\n");
                }
                String baseRules = pageLogic.generateBaseCssRules();
                if (baseRules != null && !baseRules.trim().isEmpty()) {
                    accumulatedCssBuffer.append("/* Logic Block Styles for ").append(pageName).append(" */\n");
                    accumulatedCssBuffer.append(baseRules).append("\n");
                }
                String asdCss = pageLogic.generateAsdSource("css");
                if (asdCss != null && !asdCss.trim().isEmpty()) {
                    accumulatedCssBuffer.append("/* ASD CSS source for ").append(pageName).append(" */\n");
                    accumulatedCssBuffer.append(asdCss).append("\n");
                }

                // Accumulate page-specific JS rules
                String logicJs = pageLogic.generateJavaScript();
                if (logicJs != null && !logicJs.isEmpty()) {
                    accumulatedJsBuffer.append("/* ----- logic blocks for ").append(pageName).append(" ----- */\n");
                    accumulatedJsBuffer.append(logicJs).append("\n");
                }
                String asdJs = pageLogic.generateAsdSource("js");
                if (asdJs != null && !asdJs.trim().isEmpty()) {
                    accumulatedJsBuffer.append("/* ----- user JS (ASD) for ").append(pageName).append(" ----- */\n");
                    accumulatedJsBuffer.append(asdJs).append("\n");
                }
            }
        }

        // Custom block CSS and JS
        if (customBlockManager != null) {
            String customCss = customBlockManager.renderAllCss();
            if (customCss != null && !customCss.trim().isEmpty()) {
                accumulatedCssBuffer.append("/* Custom Block Styles */\n");
                accumulatedCssBuffer.append(customCss).append("\n");
            }
        }

        // Append generated element styles
        accumulatedCssBuffer.append("/* Element Styles */\n");
        if (elementCssBuffer.length() > 0) {
            accumulatedCssBuffer.append(elementCssBuffer);
        }

        // Common JS footer
        accumulatedJsBuffer.append("/* ----- init ----- */\n");
        accumulatedJsBuffer.append("document.addEventListener('DOMContentLoaded', function() {\n");
        accumulatedJsBuffer.append("  if (window.feather) try { feather.replace(); } catch (e) {}\n");
        accumulatedJsBuffer.append("  if (window.lucide)  try { lucide.createIcons(); } catch (e) {}\n");
        accumulatedJsBuffer.append("});\n");

        String finalCssContent = accumulatedCssBuffer.toString().replace("assets/", "");
        String finalJsContent = accumulatedJsBuffer.toString().replace("assets/", "");

        File exportDir = new File(context.getFilesDir(), "exports/" + sanitizeFileName(projectName));
        if (exportDir.exists()) {
            deleteDirectory(exportDir);
        }
        exportDir.mkdirs();
        
        File cssDir = new File(exportDir, "css");
        File jsDir = new File(exportDir, "js");
        cssDir.mkdirs();
        jsDir.mkdirs();

        result.htmlContent = pageHtmlMap.get(currentPageName);
        if (result.htmlContent == null) {
            result.htmlContent = pageHtmlMap.get("index");
        }
        result.cssContent = finalCssContent;
        result.jsContent = finalJsContent;
        result.exportDir = exportDir;

        try {
            // Write HTML files in the root folder
            for (Map.Entry<String, String> entry : pageHtmlMap.entrySet()) {
                writeFile(new File(exportDir, entry.getKey() + ".html"), entry.getValue());
            }
            writeFile(new File(cssDir, "style.css"), finalCssContent);
            writeFile(new File(jsDir, "script.js"), finalJsContent);

            // Copy assets files and folders to root folder
            copyAssetsClean(exportDir);

            result.success = true;
            result.message = "Exported to: " + exportDir.getAbsolutePath();
        } catch (IOException e) {
            result.success = false;
            result.message = "Export failed: " + e.getMessage();
        }

        return result;
    }

    private void copyAssetsClean(File targetRootDir) {
        if (projectId == null || projectId.isEmpty()) return;
        try {
            String panelPath = Environment.getExternalStorageDirectory().getAbsolutePath()
                + "/.dragweb/projects/" + projectId + "/assets";
            File src = new File(panelPath);
            if (!src.exists() || !src.isDirectory()) return;

            File[] files = src.listFiles();
            if (files == null) return;
            for (File file : files) {
                if (file.isDirectory()) {
                    copyDirectory(file, new File(targetRootDir, file.getName()));
                } else {
                    copyDirectory(file, new File(targetRootDir, file.getName()));
                }
            }
        } catch (Exception e) {
            Log.w("ExportManager", "Could not mirror assets: " + e.getMessage());
        }
    }

    private String generateHtmlFromTree(List<Map<String, Object>> widgetTree, String pageName, ManageBlocksWidgets customBlockManager,
                                        LogicBlockManager logicBlockManager) {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"en\">\n");
        html.append("<head>\n");
        html.append("  <meta charset=\"UTF-8\">\n");
        html.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("  <meta name=\"description\" content=\"")
            .append(escapeHtml(pageName)).append("\">\n");
        html.append("  <meta name=\"generator\" content=\"DragWeb\">\n");
        html.append("  <title>").append(escapeHtml(pageName)).append("</title>\n");

        if (logicBlockManager != null) {
            String asdMeta = logicBlockManager.generateAsdSource("meta");
            if (asdMeta != null && !asdMeta.trim().isEmpty()) {
                html.append("  ").append(asdMeta.replace("\n", "\n  ")).append("\n");
            }
        }

        if (iconLibraryManager != null) {
            String includes = iconLibraryManager.generateHtmlIncludes();
            if (includes != null && !includes.isEmpty()) html.append(includes);
        }
        if (animationLibraryManager != null) {
            String includes = animationLibraryManager.generateHtmlIncludes();
            if (includes != null && !includes.isEmpty()) html.append(includes);
        }
        html.append("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");

        if (logicBlockManager != null) {
            String asdHead = logicBlockManager.generateAsdSource("head");
            if (asdHead != null && !asdHead.trim().isEmpty()) {
                html.append("  ").append(asdHead.replace("\n", "\n  ")).append("\n");
            }
        }

        html.append("</head>\n");
        html.append("<body>\n");

        if (widgetTree != null) {
            for (Map<String, Object> nodeMap : widgetTree) {
                html.append(generateElementHtmlFromNode(nodeMap, 1));
            }
        }

        if (customBlockManager != null) {
            String customHtml = customBlockManager.renderAllHtml();
            if (customHtml != null && !customHtml.trim().isEmpty()) {
                html.append("\n  <!-- Custom blocks -->\n  ");
                html.append(customHtml.replace("\n", "\n  "));
                html.append("\n");
            }
        }

        if (logicBlockManager != null) {
            String asdHtml = logicBlockManager.generateAsdSource("html");
            if (asdHtml != null && !asdHtml.trim().isEmpty()) {
                html.append("\n  <!-- ASD HTML source -->\n  ");
                html.append(asdHtml.replace("\n", "\n  "));
                html.append("\n");
            }
        }

        html.append("\n  <script src=\"js/script.js\" defer></script>\n");
        html.append("</body>\n");
        html.append("</html>\n");
        return html.toString();
    }

    @SuppressWarnings("unchecked")
    private String generateElementHtmlFromNode(Map<String, Object> widgetMap, int indent) {
        if (widgetMap == null) return "";

        String tag = widgetMap.containsKey("tag") ? widgetMap.get("tag").toString() : "div";
        Map<String, Object> function = (Map<String, Object>) widgetMap.get("function");
        if (function == null) return "";

        String indentStr = repeat("  ", indent);
        StringBuilder html = new StringBuilder();
        html.append(indentStr).append("<").append(tag);

        html.append(" data-widget=\"").append(tag).append("\"");

        boolean useInline = (themeManager == null || themeManager.isUseInlineStyles());
        String generatedClass = "";
        StringBuilder classAttr = new StringBuilder();

        if (useInline) {
            generatedClass = "el-" + tag + "-" + Math.abs(widgetMap.hashCode() % 10000);
            classAttr.append(generatedClass);
        }

        if (function.containsKey("class")) {
            String userClass = String.valueOf(function.get("class")).trim();
            if (!userClass.isEmpty()) {
                if (classAttr.length() > 0) classAttr.append(' ');
                classAttr.append(userClass);
            }
        }

        if (classAttr.length() > 0) {
            html.append(" class=\"").append(escapeHtml(classAttr.toString())).append("\"");
        }

        if (function.containsKey("id")) {
            String elId = String.valueOf(function.get("id")).trim();
            if (!elId.isEmpty()) html.append(" id=\"").append(escapeHtml(elId)).append("\"");
        }

        for (Map.Entry<String, Object> entry : function.entrySet()) {
            String key = entry.getKey();
            if (key.startsWith("on") && entry.getValue() != null) {
                String val = String.valueOf(entry.getValue()).trim();
                if (!val.isEmpty()) {
                    html.append(" ").append(key).append("=\"").append(escapeHtml(val)).append("\"");
                }
            }
        }

        if (useInline) {
            Map<String, Object> style = (Map<String, Object>) function.get("style");
            if (style != null && !style.isEmpty()) {
                elementCssBuffer.append('.').append(generatedClass).append(" {\n");
                for (Map.Entry<String, Object> entry : style.entrySet()) {
                    String cssKey = camelToKebab(entry.getKey());
                    elementCssBuffer.append("  ").append(cssKey).append(": ")
                        .append(entry.getValue()).append(";\n");
                }
                elementCssBuffer.append("}\n");
            }
        }

        if ("img".equals(tag) && function.containsKey("src")) {
            html.append(" src=\"").append(escapeHtml(resolveAssetPath(function.get("src").toString()))).append("\"");
            html.append(" alt=\"Image\"");
        }
        if (("input".equals(tag) || "textarea".equals(tag)) && function.containsKey("type")) {
            html.append(" type=\"").append(escapeHtml(function.get("type").toString())).append("\"");
        }
        if (("input".equals(tag) || "textarea".equals(tag)) && function.containsKey("placeholder")) {
            html.append(" placeholder=\"").append(escapeHtml(function.get("placeholder").toString())).append("\"");
        }
        if ("a".equals(tag) && function.containsKey("href")) {
            html.append(" href=\"").append(escapeHtml(function.get("href").toString())).append("\"");
        }
        if (("video".equals(tag) || "audio".equals(tag)) && function.containsKey("src")) {
            html.append(" src=\"").append(escapeHtml(function.get("src").toString())).append("\"");
        }
        if (("video".equals(tag) || "audio".equals(tag)) && "true".equals(String.valueOf(function.get("controls")))) {
            html.append(" controls");
        }
        if ("iframe".equals(tag) && function.containsKey("src")) {
            html.append(" src=\"").append(escapeHtml(function.get("src").toString())).append("\"");
        }

        if ("input".equals(tag) || "img".equals(tag) || "hr".equals(tag) || "br".equals(tag)) {
            html.append(" />\n");
            return html.toString();
        }

        html.append(">");

        if (function.containsKey("text")) {
            html.append(escapeHtml(function.get("text").toString()));
        }

        if (widgetMap.containsKey("children")) {
            Object childrenObj = widgetMap.get("children");
            if (childrenObj instanceof List) {
                List<Map<String, Object>> children = (List<Map<String, Object>>) childrenObj;
                if (!children.isEmpty()) {
                    html.append("\n");
                    for (Map<String, Object> child : children) {
                        html.append(generateElementHtmlFromNode(child, indent + 1));
                    }
                    html.append(indentStr);
                }
            }
        }

        html.append("</").append(tag).append(">\n");
        return html.toString();
    }

    private String resolveAssetPath(String rawSrc) {
        if (rawSrc == null) return "";
        if (rawSrc.startsWith("data:")) return rawSrc;
        if (rawSrc.startsWith("assets/")) return rawSrc;
        int idx = rawSrc.indexOf("/assets/");
        if (idx >= 0) {
            return "assets/" + rawSrc.substring(idx + "/assets/".length());
        }
        return rawSrc;
    }

    public File exportAsZip(View screen, String projectName, String projectId, LogicBlockManager logicBlockManager) throws IOException {
        return exportAsZip(screen, projectName, projectId, logicBlockManager, null);
    }

    public File exportAsZip(View screen, String projectName, String projectId,
                            LogicBlockManager logicBlockManager,
                            ManageBlocksWidgets customBlockManager) throws IOException {
        ExportResult result = generateExportFiles(screen, projectName, logicBlockManager, customBlockManager);
        if (!result.success) {
            throw new IOException(result.message);
        }

        String zipFileName = sanitizeFileName(projectName) + "_" + sanitizeFileName(projectId) + ".zip";

        File zipFile = null;
        try {
            String extPath = Environment.getExternalStorageDirectory().getAbsolutePath()
                + "/.DragWeb/export";
            File extDir = new File(extPath);
            if (!extDir.exists()) extDir.mkdirs();
            zipFile = new File(extDir, zipFileName);
        } catch (Exception e) {
            Log.w("ExportManager", "External storage unavailable, using internal: " + e.getMessage());
        }

        if (zipFile == null || (!zipFile.getParentFile().exists() && !zipFile.getParentFile().mkdirs())) {
            File internalDir = new File(context.getFilesDir(), "exports");
            if (!internalDir.exists()) internalDir.mkdirs();
            zipFile = new File(internalDir, zipFileName);
        }

        try (ZipOutputStream zos = new ZipOutputStream(new BufferedOutputStream(new FileOutputStream(zipFile)))) {
            zipDirectoryContents(zos, result.exportDir, "");
        }
        return zipFile;
    }

    private void zipDirectoryContents(ZipOutputStream zos, File dir, String prefix) throws IOException {
        File[] files = dir.listFiles();
        if (files == null) return;
        for (File file : files) {
            if (file.isDirectory()) {
                zipDirectoryContents(zos, file, prefix + file.getName() + "/");
            } else {
                addFileToZip(zos, prefix + file.getName(), file);
            }
        }
    }

    private void addFileToZip(ZipOutputStream zos, String entryName, File file) throws IOException {
        byte[] buffer = new byte[4096];
        try (FileInputStream fis = new FileInputStream(file)) {
            zos.putNextEntry(new ZipEntry(entryName));
            int length;
            while ((length = fis.read(buffer)) > 0) {
                zos.write(buffer, 0, length);
            }
            zos.closeEntry();
        }
    }

    private void addDirectoryToZip(ZipOutputStream zos, File dir, String prefix) throws IOException {
        File[] files = dir.listFiles();
        if (files == null) return;
        for (File file : files) {
            if (file.isDirectory()) {
                addDirectoryToZip(zos, file, prefix + file.getName() + "/");
            } else {
                addFileToZip(zos, prefix + file.getName(), file);
            }
        }
    }

    private String generateHtml(View screen, String projectName, ManageBlocksWidgets customBlockManager,
                                LogicBlockManager logicBlockManager) {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"en\">\n");
        html.append("<head>\n");
        html.append("  <meta charset=\"UTF-8\">\n");
        html.append("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("  <meta name=\"description\" content=\"")
            .append(escapeHtml(projectName)).append("\">\n");
        html.append("  <meta name=\"generator\" content=\"DragWeb\">\n");
        html.append("  <title>").append(escapeHtml(projectName)).append("</title>\n");

        // ASD <meta> additions go before icon CDN includes.
        if (logicBlockManager != null) {
            String asdMeta = logicBlockManager.generateAsdSource("meta");
            if (asdMeta != null && !asdMeta.trim().isEmpty()) {
                html.append("  ").append(asdMeta.replace("\n", "\n  ")).append("\n");
            }
        }

        if (iconLibraryManager != null) {
            String includes = iconLibraryManager.generateHtmlIncludes();
            if (includes != null && !includes.isEmpty()) html.append(includes);
        }
        if (animationLibraryManager != null) {
            String includes = animationLibraryManager.generateHtmlIncludes();
            if (includes != null && !includes.isEmpty()) html.append(includes);
        }
        html.append("  <link rel=\"stylesheet\" href=\"css/style.css\">\n");

        // ASD <head> source (e.g. extra <link> or <script src> tags) goes last
        // so it can override anything emitted above.
        if (logicBlockManager != null) {
            String asdHead = logicBlockManager.generateAsdSource("head");
            if (asdHead != null && !asdHead.trim().isEmpty()) {
                html.append("  ").append(asdHead.replace("\n", "\n  ")).append("\n");
            }
        }

        html.append("</head>\n");
        html.append("<body>\n");

        if (screen instanceof ViewGroup) {
            ViewGroup vg = (ViewGroup) screen;
            for (int i = 0; i < vg.getChildCount(); i++) {
                html.append(generateElementHtml(vg.getChildAt(i), 1));
            }
        }

        // Custom-block HTML appended into the body (after widget tree).
        if (customBlockManager != null) {
            String customHtml = customBlockManager.renderAllHtml();
            if (customHtml != null && !customHtml.trim().isEmpty()) {
                html.append("\n  <!-- Custom blocks -->\n  ");
                html.append(customHtml.replace("\n", "\n  "));
                html.append("\n");
            }
        }

        // ASD raw-HTML source blocks (authored in the Logic Blocks editor).
        if (logicBlockManager != null) {
            String asdHtml = logicBlockManager.generateAsdSource("html");
            if (asdHtml != null && !asdHtml.trim().isEmpty()) {
                html.append("\n  <!-- ASD HTML source -->\n  ");
                html.append(asdHtml.replace("\n", "\n  "));
                html.append("\n");
            }
        }

        html.append("\n  <script src=\"js/script.js\" defer></script>\n");
        html.append("</body>\n");
        html.append("</html>\n");
        return html.toString();
    }

    private String generateElementHtml(View view, int indent) {
        if (view == null) return "";

        Object tagObj = view.getTag();
        if (!(tagObj instanceof Map)) return "";

        Map<String, Object> widgetMap = (Map<String, Object>) tagObj;
        String tag = widgetMap.containsKey("tag") ? widgetMap.get("tag").toString() : "div";
        Map<String, Object> function = (Map<String, Object>) widgetMap.get("function");
        if (function == null) return "";

        String indentStr = repeat("  ", indent);
        StringBuilder html = new StringBuilder();
        html.append(indentStr).append("<").append(tag);

        // Data attribute for logic
        html.append(" data-widget=\"").append(tag).append("\"");

        // Generated class name and user class check.
        boolean useInline = (themeManager == null || themeManager.isUseInlineStyles());
        String generatedClass = "";
        StringBuilder classAttr = new StringBuilder();

        if (useInline) {
            generatedClass = "el-" + tag + "-" + Math.abs(view.hashCode() % 10000);
            classAttr.append(generatedClass);
        }

        if (function.containsKey("class")) {
            String userClass = String.valueOf(function.get("class")).trim();
            if (!userClass.isEmpty()) {
                if (classAttr.length() > 0) classAttr.append(' ');
                classAttr.append(userClass);
            }
        }

        if (classAttr.length() > 0) {
            html.append(" class=\"").append(escapeHtml(classAttr.toString())).append("\"");
        }

        if (function.containsKey("id")) {
            String elId = String.valueOf(function.get("id")).trim();
            if (!elId.isEmpty()) html.append(" id=\"").append(escapeHtml(elId)).append("\"");
        }

        // JS Event attributes
        for (Map.Entry<String, Object> entry : function.entrySet()) {
            String key = entry.getKey();
            if (key.startsWith("on") && entry.getValue() != null) {
                String val = String.valueOf(entry.getValue()).trim();
                if (!val.isEmpty()) {
                    html.append(" ").append(key).append("=\"").append(escapeHtml(val)).append("\"");
                }
            }
        }

        // Output element styles to CSS only if inline styles are enabled
        if (useInline) {
            Map<String, Object> style = (Map<String, Object>) function.get("style");
            if (style != null && !style.isEmpty()) {
                elementCssBuffer.append('.').append(generatedClass).append(" {\n");
                for (Map.Entry<String, Object> entry : style.entrySet()) {
                    String cssKey = camelToKebab(entry.getKey());
                    elementCssBuffer.append("  ").append(cssKey).append(": ")
                        .append(entry.getValue()).append(";\n");
                }
                elementCssBuffer.append("}\n");
            }
        }

        // Tag-specific attributes
        if ("img".equals(tag) && function.containsKey("src")) {
            html.append(" src=\"").append(escapeHtml(function.get("src").toString())).append("\"");
            html.append(" alt=\"Image\"");
        }
        if (("input".equals(tag) || "textarea".equals(tag)) && function.containsKey("type")) {
            html.append(" type=\"").append(escapeHtml(function.get("type").toString())).append("\"");
        }
        if (("input".equals(tag) || "textarea".equals(tag)) && function.containsKey("placeholder")) {
            html.append(" placeholder=\"").append(escapeHtml(function.get("placeholder").toString())).append("\"");
        }
        if ("a".equals(tag) && function.containsKey("href")) {
            html.append(" href=\"").append(escapeHtml(function.get("href").toString())).append("\"");
        }
        if (("video".equals(tag) || "audio".equals(tag)) && function.containsKey("src")) {
            html.append(" src=\"").append(escapeHtml(function.get("src").toString())).append("\"");
        }
        if (("video".equals(tag) || "audio".equals(tag)) && "true".equals(String.valueOf(function.get("controls")))) {
            html.append(" controls");
        }
        if ("iframe".equals(tag) && function.containsKey("src")) {
            html.append(" src=\"").append(escapeHtml(function.get("src").toString())).append("\"");
        }

        // Self-closing tags
        if ("input".equals(tag) || "img".equals(tag) || "hr".equals(tag) || "br".equals(tag)) {
            html.append(" />\n");
            return html.toString();
        }

        html.append(">");

        // Text content
        if (function.containsKey("text")) {
            html.append(escapeHtml(function.get("text").toString()));
        }

        // Children
        if (view instanceof ViewGroup) {
            ViewGroup vg = (ViewGroup) view;
            if (vg.getChildCount() > 0) {
                html.append("\n");
                for (int i = 0; i < vg.getChildCount(); i++) {
                    html.append(generateElementHtml(vg.getChildAt(i), indent + 1));
                }
                html.append(indentStr);
            }
        }

        html.append("</").append(tag).append(">\n");
        return html.toString();
    }

    private String generateCss(View screen, LogicBlockManager logicBlockManager,
                               ManageBlocksWidgets customBlockManager) {
        StringBuilder css = new StringBuilder();
        css.append("/* Generated by DragWeb */\n\n");
        css.append(themeManager.generateGlobalCss());
        css.append("\n/* Animation Keyframes */\n");
        if (animationLibraryManager != null) {
            css.append(animationLibraryManager.generateLocalKeyframesCss(""));
        } else {
            css.append(AnimationLibrary.generateKeyframesCss(""));
        }
        css.append("\n");

        // CSS pseudo-class interaction rules (hover, focus, active – no JS needed)
        if (logicBlockManager != null) {
            String pseudoRules = logicBlockManager.generateCssPseudoRules();
            if (pseudoRules != null && !pseudoRules.trim().isEmpty()) {
                css.append("/* CSS Interaction Rules */\n");
                css.append(pseudoRules);
                css.append("\n");
            }
            String baseRules = logicBlockManager.generateBaseCssRules();
            if (baseRules != null && !baseRules.trim().isEmpty()) {
                css.append("/* Logic Block Styles */\n");
                css.append(baseRules);
                css.append("\n");
            }
        }

        // Custom block CSS templates (e.g. ".menu{color:red;}" from class_color block)
        if (customBlockManager != null) {
            String customCss = customBlockManager.renderAllCss();
            if (customCss != null && !customCss.trim().isEmpty()) {
                css.append("/* Custom Block Styles */\n");
                css.append(customCss);
                css.append("\n");
            }
        }

        // ASD raw CSS source authored in the Logic Blocks editor.
        if (logicBlockManager != null) {
            String asdCss = logicBlockManager.generateAsdSource("css");
            if (asdCss != null && !asdCss.trim().isEmpty()) {
                css.append("/* ASD CSS source */\n");
                css.append(asdCss);
                css.append("\n");
            }
        }

        css.append("/* Element Styles */\n");
        if (elementCssBuffer.length() > 0) {
            css.append(elementCssBuffer);
        }
        return css.toString();
    }

    private String generateJs(LogicBlockManager logicBlockManager) {
        StringBuilder js = new StringBuilder();
        js.append("/* ==========================================================\n");
        js.append(" * DragWeb generated runtime — DO NOT edit by hand.\n");
        js.append(" * Sections: state, init, events, api, animations.\n");
        js.append(" * ========================================================== */\n\n");
        js.append("'use strict';\n\n");

        // ----- state -----
        js.append("/* ----- state ----- */\n");
        js.append("var DW = window.DW = window.DW || { state: {}, components: {} };\n\n");

        // ----- logic blocks JS (already structured by LogicBlockManager) -----
        String logicJs = logicBlockManager != null ? logicBlockManager.generateJavaScript() : "";
        if (logicJs != null && !logicJs.isEmpty()) {
            js.append("/* ----- logic blocks ----- */\n");
            js.append(logicJs).append("\n");
        }

        // ----- ASD raw JS source authored in the Logic Blocks editor -----
        String asdJs = logicBlockManager != null ? logicBlockManager.generateAsdSource("js") : "";
        if (asdJs != null && !asdJs.trim().isEmpty()) {
            js.append("\n/* ----- user JS (ASD) ----- */\n");
            js.append(asdJs).append("\n");
        }

        // ----- init -----
        js.append("/* ----- init ----- */\n");
        js.append("document.addEventListener('DOMContentLoaded', function() {\n");
        js.append("  // Re-initialise icon libraries (no-op if not loaded).\n");
        js.append("  if (window.feather) try { feather.replace(); } catch (e) {}\n");
        js.append("  if (window.lucide)  try { lucide.createIcons(); } catch (e) {}\n");
        js.append("});\n");
        return js.toString();
    }

    private void writeFile(File file, String content) throws IOException {
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(content);
        }
    }

    private void addToZip(ZipOutputStream zos, String fileName, String content) throws IOException {
        ZipEntry entry = new ZipEntry(fileName);
        zos.putNextEntry(entry);
        zos.write(content.getBytes("UTF-8"));
        zos.closeEntry();
    }

    public boolean importZipBackup(File zipFile) {
        if (zipFile == null || !zipFile.exists()) return false;
        
        File projectDir = new File(context.getFilesDir(), "projects");
        if (!projectDir.exists()) projectDir.mkdirs();
        
        try (java.util.zip.ZipInputStream zis = new java.util.zip.ZipInputStream(new FileInputStream(zipFile))) {
            ZipEntry entry;
            byte[] buffer = new byte[4096];
            while ((entry = zis.getNextEntry()) != null) {
                String name = entry.getName();
                
                if (name.startsWith("data/")) {
                    String fileName = name.substring(5);
                    File target = new File(projectDir, fileName);
                    try (FileOutputStream fos = new FileOutputStream(target)) {
                        int len;
                        while ((len = zis.read(buffer)) > 0) fos.write(buffer, 0, len);
                    }
                } else if (name.startsWith("assets/")) {
                    // Extract to external storage assets path
                    // We need the projectId from the filename if possible, but the ZIP itself 
                    // should ideally contain it in a meta file or we infer it.
                    // For now, let's assume we find a .json file in data/ first or just extract assets
                    // to a temporary location then move them once we know the projectId.
                    // Or better: the zip structure is assets/projectId/...
                    
                    // Actually, let's look for any .json file in data/ to find the projectId
                    // This is tricky during streaming.
                    
                    // Simple approach: Extract everything to a temp dir, then find the .json file, then move.
                }
                zis.closeEntry();
            }
            return true;
        } catch (IOException e) {
            Log.e("ExportManager", "Import failed: " + e.getMessage());
            return false;
        }
    }

    // Better import logic: extract all to temp, then move to right places
    public boolean restoreProjectFromZip(File zipFile) {
        File tempDir = new File(context.getCacheDir(), "import_temp_" + System.currentTimeMillis());
        tempDir.mkdirs();
        
        try (java.util.zip.ZipInputStream zis = new java.util.zip.ZipInputStream(new FileInputStream(zipFile))) {
            ZipEntry entry;
            byte[] buffer = new byte[4096];
            while ((entry = zis.getNextEntry()) != null) {
                File file = new File(tempDir, entry.getName());
                if (entry.isDirectory()) {
                    file.mkdirs();
                } else {
                    file.getParentFile().mkdirs();
                    try (FileOutputStream fos = new FileOutputStream(file)) {
                        int len;
                        while ((len = zis.read(buffer)) > 0) fos.write(buffer, 0, len);
                    }
                }
                zis.closeEntry();
            }
            
            // Now move from temp to actual locations
            File dataDir = new File(tempDir, "data");
            String foundProjectId = null;
            if (dataDir.exists()) {
                File[] files = dataDir.listFiles();
                if (files != null) {
                    for (File f : files) {
                        if (f.getName().endsWith(".json")) {
                            String possibleId = f.getName().replace(".json", "");
                            File metaFile = new File(dataDir, possibleId + ".meta");
                            if (metaFile.exists()) {
                                foundProjectId = possibleId;
                                break;
                            }
                        }
                    }
                    
                    if (foundProjectId != null) {
                        // Move data files
                        File targetDataDir = new File(context.getFilesDir(), "projects");
                        targetDataDir.mkdirs();
                        for (File f : files) {
                            f.renameTo(new File(targetDataDir, f.getName()));
                        }
                        
                        // Move assets
                        File assetsDir = new File(tempDir, "assets");
                        if (assetsDir.exists()) {
                            String targetAssetsPath = Environment.getExternalStorageDirectory().getAbsolutePath()
                                + "/.dragweb/projects/" + foundProjectId + "/assets";
                            File targetAssetsDir = new File(targetAssetsPath);
                            targetAssetsDir.mkdirs();
                            copyDirectory(assetsDir, targetAssetsDir);
                        }
                        return true;
                    }
                }
            }
        } catch (Exception e) {
            Log.e("ExportManager", "Restore failed: " + e.getMessage());
        } finally {
            deleteDirectory(tempDir);
        }
        return false;
    }

    private void copyDirectory(File sourceLocation, File targetLocation) throws IOException {
        if (sourceLocation.isDirectory()) {
            if (!targetLocation.exists() && !targetLocation.mkdirs()) {
                throw new IOException("Cannot create dir " + targetLocation.getAbsolutePath());
            }
            String[] children = sourceLocation.list();
            for (int i = 0; i < children.length; i++) {
                copyDirectory(new File(sourceLocation, children[i]),
                        new File(targetLocation, children[i]));
            }
        } else {
            java.io.InputStream in = new FileInputStream(sourceLocation);
            java.io.OutputStream out = new FileOutputStream(targetLocation);
            byte[] buf = new byte[1024];
            int len;
            while ((len = in.read(buf)) > 0) {
                out.write(buf, 0, len);
            }
            in.close();
            out.close();
        }
    }

    private void deleteDirectory(File path) {
        if (path.exists()) {
            File[] files = path.listFiles();
            if (files != null) {
                for (File file : files) {
                    if (file.isDirectory()) deleteDirectory(file);
                    else file.delete();
                }
            }
            path.delete();
        }
    }

    private String escapeHtml(String text) {
        if (text == null) return "";
        return text.replace("&", "&amp;")
                   .replace("<", "&lt;")
                   .replace(">", "&gt;")
                   .replace("\"", "&quot;");
    }

    private String camelToKebab(String str) {
        if (str == null) return "";
        return str.replaceAll("([A-Z])", "-$1").toLowerCase();
    }

    private String sanitizeFileName(String name) {
        if (name == null) return "project";
        return name.replaceAll("[^a-zA-Z0-9._-]", "_");
    }

    private String repeat(String str, int count) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < count; i++) {
            sb.append(str);
        }
        return sb.toString();
    }
}
